server:
  port: 8080

spring:

  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    tomcat:
      test-on-borrow: true
      validation-query: SELECT 1

  jpa:
    properties:
      hibernate:
        default_schema: notification_service
    hibernate:
      ddl-auto: validate
  flyway:
    schemas: notification_service
    baseline-on-migrate: true
    baseline-version: 0
  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
# Kafka
kafka:
  bootstrapServers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  groupId: ${KAFKA_CARD_GROUP_ID:notification-group}
  clientId: ${KAFKA_CARD_CLIENT_ID:notification-client}
  acksConfig: ${KAFKA_ACKS_CONFIG:all}
  retriesConfig: ${KAFKA_RETRIES_CONFIG:3}
  lingerMsConfig: ${KAFKA_LINGER_MS_CONFIG:100}
  clientDnsLookup: ${KAFKA_CLIENT_DNS_LOOKUP:use_all_dns_ips}
  batchSizeConfig: ${KAFKA_BATCH_SIZE_CONFIG:16384}
  bufferMemoryConfig: ${KAFKA_BUFFER_MEMORY_CONFIG:32768}
  autoOffsetResetConfig: ${KAFKA_AUTO_OFFSET_RESET_CONFIG:earliest}
  saslProtocol: ${KAFKA_SASL_PROTOCOL}
  saslMechanism: ${KAFKA_SASL_MECHANISM}
  saslUsername: ${KAFKA_SASL_USERNAME}
  saslPassword: ${KAFKA_SASL_PASSWORD}
  topics:
    notification: ${KAFKA_NOTIFICATION_TOPIC:notifications}

logging:
  level:
    uz.mukhammadjon.notification_service: DEBUG
    org.springframework.web: DEBUG
    org.flywaydb.core.internal.scanner: DEBUG
